--- #YAML:1.0
name:               Geo-SpaceManager
version:            0.93
abstract:           Place rectangles without overlap
author:
    - Jim Gibson (Jim@Gibson.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Number::Delta:  0.16
    Test::Simple:         0.62
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
